### ISSUE TITLE
v2.0 support

### ISSUE THREAD

**Issue by Davincible** [sugarme/gotch#100]
I know its early but any plans on supporting v2.0?

**Comment by sugarme** [comment]
@Davincible,

Yes, we plan to upgrade Go APIs for libtorch v2 in coming weeks.

**Comment by liufuyang** [comment]
Thanks a lot. Would this happen soon? And I am having difficulty to the current version working on a Mac M1 (as I cannot get pytorch v1.11.0 built for ARM). I guess upgrading onto v2 can unblock a lot of things as I should be able to download or build one without much difficulty? 🤔

**Comment by sugarme** [comment]
upgraded to libtorch 2.1
