### ISSUE TITLE
how to load model pytorch_model.bin

### ISSUE THREAD

**Issue by hzylyq** [sugarme/gotch#103]
Is there anyway to direct load model, such as pytorch_model.bin

**Comment by sugarme** [comment]
@hzylyq, 

Yes. You can load (unpickle) Pytorch model bin using subpackage 'pickle'. 

See example at https://github.com/sugarme/gotch/blob/7153719f596ffadabba1272730c2edf2bc8f0ce6/example/pickle/main.go

**Comment by hzylyq** [comment]
well, how load m3e-base model.https://huggingface.co/moka-ai/m3e-base

**Comment by hzylyq** [comment]
`
err := pickle.LoadInfo("/home/huzhiyang/pytorch_model.bin")
	if err != nil {
		log.Fatal(err)
	}`
 LoadInfo() failed: Decode() failed: expected 'OrderedDict' type, got *pickle.Dict
exit status 1
It's fail

**Comment by hzylyq** [comment]
I unzip pytorch_model.bin and I use ts api.still got an error.
`
_, err := ts.Load("/home/huzhiyang/pytorch_model/data.pkl")
if err != nil {
	log.Fatal(err)
}
`
 Libtorch API Error: `torch::jit::load()` received a file from `torch.save()`, but `torch::jit::load()` can only load files produced by `torch.jit.save()`

**Comment by sugarme** [comment]
close for now. If you want to see example, please see the folder in `example` folder or other previous closed issues.
