### ISSUE TITLE
Indexing documentation

### ISSUE THREAD

**Issue by vbugaevskii** [sugarme/gotch#104]
Hello,

I really appreciate your library, thank you. I understand it's a highly developing project, so sometimes documentation is not full.

So my question is how can I index a tensor in your library? Particularly, I have problems with such case (taking a column):

```python
import torch

a = [[1, 2, 3], [4, 5, 6]]
a = torch.Tensor(a)
a[:, 2]
```

Thank you in advance.

**Comment by sugarme** [comment]
@vbugaevskii,

Basically gotch tensor indexing using 2 operations `Select` and `Narrow`. See the solution below. Feel free to add tensor indexing documentation in a PR. Thanks

```go
package main

import (
        "fmt"

        "github.com/sugarme/gotch/ts"
)

func main() {
        x := ts.MustOfSlice([]float32{1, 2, 3, 4, 5, 6}).MustView([]int64{2, 3}, true)
        x1 := x.MustSelect(1, 2, false)
        x.Print()
        fmt.Printf("x[:,2]:\n%v\n", x1)
}

```
Output:

```bash
 1  2  3
 4  5  6
[ CPUFloatType{2,3} ]
x[:,2]:
3  6  

```
