### ISSUE TITLE
how can i convert gocv.Mat image data to Tensor ?

### ISSUE THREAD

**Issue by zombie-k** [sugarme/gotch#119]
i read image use gocv.IMRead, it's a gocv.Mat, after some steps to process the gocv.Mat data, how can i convert (gocv.Mat) to (ts.Tensor) ?

**Comment by sugarme** [comment]
@zombie-k ,

I don't know what kind of data `gocv.Mat` is but you can create a `ts.Tensor` using API `ts.OfSlice(data []T)` where data is backing slice and reshape it to original shape. There also other API `ts.NewTensorFromData()` where you can specify shape and dtype.

Hope that helps.

**Comment by sugarme** [comment]
close for now. If you still have issue, please provide further detail.
