### ISSUE TITLE
Unknown builtin op: torchvision::nms

### ISSUE THREAD

**Issue by RobinFrcd** [sugarme/gotch#134]
Hi,
I'm trying to load a TorchScript model that contains the [nms](https://pytorch.org/vision/main/generated/torchvision.ops.nms.html) function from vision.

Thing is, the model call fails because Libtorch can't find this function:
```
Libtorch API Error: 
Unknown builtin op: torchvision::nms.
Could not find any similar ops to torchvision::nms. This op may not exist or may not be currently supported in TorchScript.
:
  File "code/__torch__/torchvision/ops/boxes.py", line 136
  _42 = __torch__.torchvision.extension._assert_has_ops
  _43 = _42()
  _44 = ops.torchvision.nms(boxes, scores, iou_threshold)
        ~~~~~~~~~~~~~~~~~~~ <--- HERE
  return _44
```

I've imported both:
```
	"github.com/sugarme/gotch/ts"
	"github.com/sugarme/gotch/vision"
```

Not sure the setup for libtorch also includes libtorchvision. 

Thanks for your help !

**Comment by sugarme** [comment]
@RobinFrcd ,

Gotch has just wrapped libtorch therefore, I think it does not cover `torchvision`, unfortunately. Thanks for your report.
