### ISSUE TITLE
[Question] Is it possible to load *.pkl model?

### ISSUE THREAD

**Issue by Claus1** [sugarme/gotch#22]
I trained a model and export it as export.pkl file (ResNet50). When try to load it I get the error:
Libtorch API Error: [enforce fail at inline_container.cc:222] . file not found: archive/constants.pkl
Is it possible to load such file?

**Comment by sugarme** [comment]
Hi @Claus1 ,

Gotch cannot load Python model saved in `.pkl` format. However, there are 2 options for a Pytorch model to be loaded with `gotch`:
1.  Save it in numpy format (`.npz`) then load it with `tensor.ReadNpz` method. There are [an example here](https://github.com/sugarme/gotch/blob/master/example/convert-model/main.go)
2. or save [JIT format](https://pytorch.org/docs/stable/generated/torch.jit.save.html) then you can load JIT model with `gotch` even fine-tuning model as well. There are [example here](https://github.com/sugarme/gotch/tree/master/example/jit) and [here](https://github.com/sugarme/gotch/tree/master/example/jit-train).

Hope that helps.

**Comment by Claus1** [comment]
Thanks a lot!!
