### ISSUE TITLE
How to load pretrained pytorch model.

### ISSUE THREAD

**Issue by shabashaash** [sugarme/gotch#50]
Sorry for my stupidity, but i cant understand how to load model trained with pytorch? I have .pth file and can rewrite model.py file on GO (or save it to .pt with scripting), but how to do it generally?

**Comment by sugarme** [comment]
Hi @shabashaash 

There're 2 ways to load Python Pytorch model with gotch:
1. Convert Python model to numpy (.npz) then gotch provides `ts.ReadNpz` method to read .npz file. See [example/convert-model](https://github.com/sugarme/gotch/blob/master/example/convert-model/main.go).
2. Save model to [JIT](https://pytorch.org/docs/stable/generated/torch.jit.save.html) then gotch provides APIs for both inferring and finetuning/training model. See example [here](https://github.com/sugarme/gotch/tree/master/example/jit) and [here](https://github.com/sugarme/gotch/tree/master/example/jit-train)

**Comment by shabashaash** [comment]
Sorry again i know this isn't a stackoverflow or somethin, but I would really appreciate your help. 
I saved model to ".npz" then to ".pt".

My model is EraseNet (its a GAN with VGG16 as feature extractor).

When i'm try to forward pass it I get this error: https://imgur.com/a/D6PpgaG

This is my code


```
        imageNet := vision.NewImageNet()

	device := gotch.CudaIfAvailable()

	image, err := imageNet.LoadImage("path/to/img.jpg")
	imageTs, err := vision.Resize(image, 512, 512)

	usimage := imageTs.MustUnsqueeze(int64(0), false)

	Img := usimage.MustTo(device, true)

	if err != nil {
		log.Fatal(err)
	}
	model, err := ts.ModuleLoad("path/to/model.pt")
	if err != nil {
		log.Fatal(err)
	}
	output := Img.ApplyCModule(model)
	fmt.Printf("done")
	fmt.Printf("%8.3f\n", output)
```

**Comment by sugarme** [comment]
@shabashaash ,

Look like your model weights loaded to CPU. Can you try to `forward` image from CPU as well to see how you go first.

**Comment by shabashaash** [comment]
@sugarme,
thx for reply, but i fixed this error (idk why but model.cuda() did not convert all modules to cuda and i have to do it manually).
I think i managed to load the model successfully, buuuuut yet again something went wrong.

Output of my U-Net part of the model looks like this.
![Screenshot from 2021-07-22 02-07-44](https://user-images.githubusercontent.com/43162766/126571063-25e8c4a6-dced-4105-88fe-34fcd85b7387.png)
 But outputs of other layers look much more normal. (Believe me this looks MUUUCH more like the ref image).
![Screenshot from 2021-07-22 02-09-43](https://user-images.githubusercontent.com/43162766/126571179-c8e5bab5-6954-4243-80a3-9afb57ba1d0a.png)
Also when im trying to load .pt in python i get even worse results:
![Screenshot from 2021-07-22 02-36-33](https://user-images.githubusercontent.com/43162766/126572843-a666fbd2-ef4a-4573-b943-36c5863767fe.png)
![Screenshot from 2021-07-22 02-36-07](https://user-images.githubusercontent.com/43162766/126572847-2ac7bdd7-043a-4c76-b730-21b1925af2c8.png)

So its more likely a scripting problem and not the library. I would appreciate the help but i think i should ask somewhere else.
