### ISSUE TITLE
How to convert lib.Ctensor to Tensor outside the tensor package？

### ISSUE THREAD

**Issue by FelixHo** [sugarme/gotch#58]
when `ForwardIs` returns a pytorch Tensor type from the PyTorch JIT model , according to the code below, 
https://github.com/sugarme/gotch/blob/master/tensor/jit.go#L449-L457
```go
tensor := lib.AtiToTensor(cval.civalue) // <-----lib.Ctensor
if err := TorchErr(); err != nil {
	return nil, err
}
return &IValue{
	value: tensor, // ---> It might be better to change this to x Tensor{tensor} 
	kind:  TensorVal,
	name:  "Tensor",
}, nil
```

the value of IValue is the lib.Ctensor type , as far as I know (im new to golang), I cannot convert it to Tensor type outside the `tensor` package because the `ctensor` of `type Tensor` is not exported.
```go
type Tensor struct {
	ctensor lib.Ctensor
}
```

**Comment by sugarme** [comment]
Hi @FelixHo,

Thanks for pointing it out. I'll fix it shortly.
