### ISSUE TITLE
bugfix cuda_device_cnt

### ISSUE THREAD

**Issue by ZonghaoWang** [sugarme/gotch#67]
![image](https://user-images.githubusercontent.com/11403656/154785659-1f47d68b-6ad7-4175-978c-0f58ba983882.png)
for atc_cuda_device_count return int32 value, so the code should be change to
![image](https://user-images.githubusercontent.com/11403656/154785680-1e8bae03-a72f-4453-81c1-4584987c3817.png)

**Comment by sugarme** [comment]
@ZonghaoWang ,

Thanks for the report!
