### ISSUE TITLE
error in setup-libtorch.sh

### ISSUE THREAD

**Issue by XiongUp** [sugarme/gotch#73]
```
#!/bin/bash

LIBTORCH_VERSION="${LIBTORCH_VER:-1.11.0}"
CUDA_VERSION="${CUDA_VER:-11.3}"
echo ${CUDA_VERSION}
if [ "${CUDA_VERSION}"=="cpu" ]; then
  CU_VERSION="cpu"
else
  CU_VERSION="cu${CUDA_VERSION//./}"
fi
echo ${CU_VERSION}
```
No matter what CUDA VER is entered, CU VERSION is always cpu.
There is an error in if, it should be `if [ "${CUDA_VERSION}" == "cpu" ]; then`. In other words, two Spaces are missing.

**Comment by sugarme** [comment]
@XiongUp ,

Thanks for the report. It's a regression from previous update. Will update shortly.
