### ISSUE TITLE
Best way to serialize tensor into bytes?

### ISSUE THREAD

**Issue by StrongerXi** [sugarme/gotch#83]
As title. This is useful for transferring tensor over network, which should be a common thing given golang's typical use cases.

Right now I'm using the following, but it involves some unnecessary file io.

https://github.com/sugarme/gotch/blob/17f2c49e34bae28fe0ef899291b5c759080c661c/ts/tensor.go#L800-L804

**Comment by sugarme** [comment]
@StrongerXi ,

Yeah, there're 2 APIs `ts.Save()` and `ts.SaveMultiNew()`  to save tensor(s). They are just wrappers to libtorch APIs. I have no issue to load/save my trained models by using them. Would you mind sharing what are your use cases? and what issues are you facing?

**Comment by StrongerXi** [comment]
Sorry I should've clarified. I'm trying to serialize tensors (not models), transmit over network, and deserialize. Use case is distributed inference, for a very naive class project:)

**Comment by sugarme** [comment]
@StrongerXi,

Ok I got you. Basically, tensor data is in C memory, and handling data between C and Go is quite expensive in terms of performance. Also, reconstruct tensor (deserialize) will double the cost. I don't have a clearly optimal way, but you can try to get tensor data with `ts.Values()` then serialize your data if you want to wire things up with Go.

There must be much better ways and I am happy to know about.

**Comment by StrongerXi** [comment]
Thanks. Seems like we just have to add a wrapper to the `torch::save(tensor, std::ostream)` API (see [this](https://github.com/pytorch/pytorch/issues/19025#issuecomment-482308272)).

I might send in a PR if this really becomes a performance issue in my project. Else I'll close this issue:).

**Comment by sugarme** [comment]
close this issue for now as no response.
