### ISSUE TITLE
go mod tidy trying to search for 'github.com/sugarme/gotch/tensor' which does not exist

### ISSUE THREAD

**Issue by luxiant** [sugarme/gotch#93]
I'm experiencing a wierd problem when trying to import the package. I got this error in the terminal.

(luxiant) luxiant@localhost:~/Documents/projects/KoBERT> go mod tidy
go: finding module for package github.com/golang/mock/gomock
go: finding module for package github.com/sugarme/gotch/tensor
go: found github.com/golang/mock/gomock in github.com/golang/mock v1.6.0
go: finding module for package github.com/sugarme/gotch/tensor
KoBERT imports
        github.com/sugarme/transformer/bert imports
        github.com/sugarme/gotch/tensor: module github.com/sugarme/gotch@latest found (v0.7.0), but does not contain package github.com/sugarme/gotch/tensor

Why is the terminal try to search for that? /tensor is not the submodule in the current module, and I did not import that in my code either. So the terminal is not supposed to search for that, but it does.

Why is this happening?

**Comment by sugarme** [comment]
@luxiant ,

From provided `go mod tidy` log, you was using `github.com/sugarme/transformer` which depends on `github.com/sugarme/gotch v0.0.0-20200924012111-ff31d3c62dbe` while your `KoBERT` tried to update `github.com/sugarme/gotch@latest` that causes the conflict.

the subpackage `github.com/sugarme/gotch/tensor` has been changed to `github.com/sugarme/gotch/ts` in newer version of gotch but `github.com/sugarme/transformer` still using older version which is `github.com/sugarme/gotch/tensor`. 

Please try `go get github.com/sugarme/gotch v0.0.0-20200924012111-ff31d3c62dbe` to use older gotch version. 

The package `github.com/sugarme/transformer` will be received a major update in the near future with many latest useful models but you have to wait. 

Hope that helps.

**Comment by sugarme** [comment]
@luxiant ,

I have just updated `github.com/sugarme/transformer` to current gotch version (v0.7.0). If you do 

```bash
go get github.com/sugarme/transformer@v0.2.0

go mod tidy

```

Hope that works.

**Comment by sugarme** [comment]
Close this issue for now. Feel free to open if concern.
